# -*- coding: utf-8 -*-
"""PenguinsCapToxG Audit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-UBa4lt3qnGju91LanIDGsB75F0bNqr
"""

import pandas as pd
#import data from puckpedia and moneypuck
df_cap = pd.read_csv('PenguinsCap.csv')
df_mp_raw = pd.read_csv('skaters.csv')
#rename cap file columns
df_cap.columns = ['Player', 'Age', 'Position', '2026_Cap_Hit']
#filter for penguins playersin 2026-27 on 5on5 situations
df_mp_5on5 = df_mp_raw[df_mp_raw['situation'] == '5on5'].copy()
df_mp_clean = df_mp_5on5[['name', 'I_F_xGoals','icetime']].copy()
#change the column in moneypuck to Player
df_mp_clean.rename(columns={'name':'Player'}, inplace=True)
#merge last year player stats by name to this years cap numbers
df_merged = pd.merge(df_cap, df_mp_clean, on='Player', how='inner')
#find the percentage of cap used by player
df_merged['Cap_Hit_Percentage'] = (df_merged['2026_Cap_Hit'] / 104000000) * 100
#calculate the economic metric of 5on5 xgoals per 1% of cap space
df_merged['xG_per_Cap_Percent'] = df_merged['I_F_xGoals'] / df_merged['Cap_Hit_Percentage']
#sort most to least efficient
df_merged = df_merged.sort_values(by='xG_per_Cap_Percent', ascending=False)
#output final csv
df_merged.to_csv('penguins_cap_efficiency.csv', index=False)

import matplotlib.pyplot as plt
import seaborn as sns

#clean up positions
df_merged['Position_Group'] = df_merged['Position'].apply(
    lambda x: 'Defense' if 'D' in str(x) else 'Forward'
    )

#visual style
sns.set_theme(style="whitegrid")
plt.figure(figsize=(12,8))

#create scatterplot
ax = sns.scatterplot(
    data=df_merged,
    x='Cap_Hit_Percentage',
    y='I_F_xGoals',
    hue='Position_Group',
    style='Position_Group',
    s=180,
    palette={'Forward': '#1f77b4', 'Defense': '#ff7f0e'}
)

#annotate player names over the plot
for i in range(df_merged.shape[0]):
  row = df_merged.iloc[i]
  if row['xG_per_Cap_Percent'] > df_merged['xG_per_Cap_Percent'].median() or row['Cap_Hit_Percentage'] > 5:
    plt.text(
        x=row['Cap_Hit_Percentage'] + 0.12,
        y=row['I_F_xGoals'] + 0.05,
        s=row['Player'],
        fontsize=9.5,
        weight='semibold' if row['Player'] in ['Ben Kindel','Justin Brazeau','Elmer Söderblom'] else 'normal'
    )

#key moved off plot
plt.legend(
    title='Roster Group',
    bbox_to_anchor=(1.02, 1),
    loc='upper left',
    borderaxespad=0,
    fontsize=11,
    title_fontsize=12
)

#adding titles and descriptive labels
plt.title('Pittsburgh Penguins: 2026-27 Roster Cap Efficiency', fontsize=16, weight='bold', pad=15)
plt.xlabel('Resource Consumption (% of $104M Salary Cap)', fontsize=12, labelpad=10)
plt.ylabel('5on5 Even Strength Individual Expected Goals (ixG 2025)', fontsize=12, labelpad=10)

#formatting
plt.xlim(0, df_merged['Cap_Hit_Percentage'].max() + 1)
plt.ylim(0, df_merged['I_F_xGoals'].max() + 1.5)

#Save as PNG
plt.savefig('penguins_cap_efficiency_plot.png', dpi=300, bbox_inches='tight')
plt.show()